name: forumapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/p96.png" 

 
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

 
